routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::resource('employee', 'EmployeeController', ['except' => ['show']]);
	Route::resource('task', 'TaskController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    const STATUS_NEW = 1;
    const STATUS_IN_PROGRESS = 2;
    const STATUS_DONE = 3;
    const STATUS_NOT_NECESSARY = 4;

    protected $guarded = [];

    public function employee()
    {
        return $this->belongsTo(Employee::class,'assigned_to', 'id');
    }

    public function getShortMessage()
    {
        return strlen($this->message) > 20 ? substr($this->message, 0, 20) . '...' : $this->message;
    }
}

app/Http/Controllers/Api/TaskController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\TaskRequest;
use App\Task;
use Illuminate\Http\Request;

class TaskController extends Controller
{
    /**
     * Update the specified task in storage
     *
     * @param  \App\Http\Requests\TaskRequest  $request
     * @param  \App\Task  $task
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(TaskRequest $request, Task  $task)
    {
        $task->update($request->all());

        return redirect()->route('user.index')->withStatus(__('Task successfully updated.'));
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Employee;
use App\Task;
use App\Http\Requests\TaskRequest;

class TaskController extends Controller
{
    /**
     * Display a listing of the tasks
     *
     * @param  \App\Task  $model
     * @return \Illuminate\View\View
     */
    public function index(Task $task)
    {
        return view('tasks.index', ['tasks' => $task->paginate(15)]);
    }

    /**
     * Show the form for creating a new task
     *
     * @return \Illuminate\View\View
     */
    public function create(Employee $employee)
    {
        return view('tasks.create', ['employees' => $employee->all()]);
    }

    /**
     * Store a newly created task in storage
     *
     * @param  \App\Http\Requests\TaskRequest  $request
     * @param  \App\Task  $task
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(TaskRequest $request, Task $task)
    {
        $task->create(array_merge($request->all(), ['status' => Task::STATUS_NEW,'assigned_by' => auth()->user()->id, 'deadline' => now()->addHours(8)]));

        return redirect()->route('task.index')->withStatus(__('Task successfully created.'));
    }

    /**
     * Show the form for editing the specified task
     *
     * @param  \App\Task  $task
     * @return \Illuminate\View\View
     */
    public function edit(Task $task)
    {
        return view('tasks.edit', compact('task'));
    }

    /**
     * Update the specified task in storage
     *
     * @param  \App\Http\Requests\TaskRequest  $request
     * @param  \App\Task  $task
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(TaskRequest $request, Task  $task)
    {
        $task->update(
            $request->merge(['password' => Hash::make($request->get('password'))])
                ->except([$request->get('password') ? '' : 'password']
                ));

        return redirect()->route('user.index')->withStatus(__('Task successfully updated.'));
    }

    /**
     * Remove the specified task from storage
     *
     * @param  \App\Task  $task
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Task  $task)
    {
        $task->delete();

        return redirect()->route('user.index')->withStatus(__('Task successfully deleted.'));
    }
}

resources/views/tasks/create.blade.php
@extends('layouts.app', ['title' => __('Tasks Management')])

@section('content')
    @include('tasks.partials.header', ['title' => __('Add Task')])

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Tasks Management') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('task.index') }}" class="btn btn-sm btn-primary">{{ __('Back to list') }}</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('task.store') }}" autocomplete="off">
                            @csrf

                            <h6 class="heading-small text-muted mb-4">{{ __('Task information') }}</h6>
                            <div class="pl-lg-4">
                                <div class="form-group{{ $errors->has('assigned_to') ? ' has-danger' : '' }}">
                                    <label for="input-assigned-to">Employee</label>
                                    <select class="custom-select" id="input-assigned-to" name="assigned_to">
                                        @foreach($employees as $employee)
                                            <option value="{{ $employee->id }}">{{ $employee->user->first_name . " " . $employee->user->last_name }}</option>
                                        @endforeach
                                    </select>
                                    @if ($errors->has('assigned_to'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('assigned_to') }}</strong>
                                        </span>
                                    @endif
                                </div>

                                <div class="form-group{{ $errors->has('message') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-message">{{ __('Message') }}</label>
                                    <textarea name="message" id="input-message" class="form-control form-control-alternative{{ $errors->has('message') ? ' is-invalid' : '' }}" placeholder="{{ __('Message') }}" required rows="4">{{ old('message') }}</textarea>

                                    @if ($errors->has('message'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('message') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="text-right">
                                    <button type="submit" class="btn btn-success mt-4">{{ __('Save') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/tasks/edit.blade.php
@extends('layouts.app', ['title' => __('Task Management')])

@section('content')
    @include('tasks.partials.header', ['title' => __('Edit Task')])

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Task Management') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('task.index') }}" class="btn btn-sm btn-primary">{{ __('Back to list') }}</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('task.update', $task) }}" autocomplete="off">
                            @csrf
                            @method('put')

                            <h6 class="heading-small text-muted mb-4">{{ __('Task information') }}</h6>
                            <div class="pl-lg-4">
                                <div class="form-group{{ $errors->has('message') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-message">{{ __('Message') }}</label>
                                    <textarea name="message" id="input-message" class="form-control form-control-alternative{{ $errors->has('message') ? ' is-invalid' : '' }}" placeholder="{{ __('Message') }}" required rows="4">{{ $task->message }}</textarea>

                                    @if ($errors->has('message'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('message') }}</strong>
                                        </span>
                                    @endif
                                </div>

                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4">{{ __('Save') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/tasks/index.blade.php
@extends('layouts.app', ['title' => __('Task Management')])

@section('content')
    @include('layouts.headers.cards')

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Tasks') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('task.create') }}" class="btn btn-sm btn-primary">{{ __('Add task') }}</a>
                            </div>
                        </div>
                    </div>

                    <div class="col-12">
                        @if (session('status'))
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ session('status') }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @endif
                    </div>

                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                            <tr>
                                <th scope="col">{{ __('Employee') }}</th>
                                <th scope="col">{{ __('Task') }}</th>
                                <th scope="col">{{ __('Status') }}</th>
                                <th scope="col"></th>
                            </tr>
                            </thead>
                            <tbody>
                            @if($tasks->count() > 0)
                                @foreach ($tasks as $task)
                                    <tr>
                                        <td>{{ $task->employee->user->first_name . " " . $task->employee->user->last_name }}</td>
                                        <td>{{ $task->getShortMessage() }}</td>
                                        <td>{{ $task->status }}</td>
                                        <td class="text-right">
                                            <div class="dropdown">
                                                <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    <i class="fas fa-ellipsis-v"></i>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                    <form action="{{ route('task.destroy', $task) }}" method="post">
                                                        @csrf
                                                        @method('delete')

                                                        <a class="dropdown-item" href="{{ route('task.edit', $task) }}">{{ __('Edit') }}</a>
                                                        <button type="button" class="dropdown-item" onclick="confirm('{{ __("Are you sure you want to delete this task?") }}') ? this.parentElement.submit() : ''">
                                                            {{ __('Delete') }}
                                                        </button>
                                                    </form>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            @else
                                <tr>
                                    <td class="text-center text-muted" colspan="3">{{ __("No tasks yet. Do you want to create one?") }}</td>
                                </tr>
                            @endif
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer py-4">
                        <nav class="d-flex justify-content-end" aria-label="...">
                            {{ $tasks->links() }}
                        </nav>
                    </div>
                </div>
            </div>
        </div>

        @include('layouts.footers.auth')
    </div>
@endsection